### ISSUE TITLE
version control

### ISSUE THREAD

**Issue by czogran** [twiniars/MeROS#1]
The inclusion of an editable version of the project (in the form of Markdown or text files) within the repository is crucial to facilitate the tracking of changes across various versions and adding pull requests. Additionally, the addition of a changelog file would serve as a valuable asset, providing a comprehensive record of modifications made over time.

**Comment by twiniars** [comment]
At the project's current stage, MeROS will be provided in particular versions as pdf files created from LaTeX. Changelogs are also planned.

**Comment by twiniars** [comment]
@czogran Maybe you can handle it as a contribution https://github.com/twiniars/MeROS/issues/7
