### ISSUE TITLE
Migrate from abbreviations to descriptive names

### ISSUE THREAD

**Issue by czogran** [twiniars/MeROS#16]
As on the below diagram in one place, Service is abbreviated to Srv, in another place not:  
![image](https://github.com/twiniars/MeROS/assets/26524922/c1302e91-d38c-4e40-9ded-9277b929ff4b)    

After the first glance on NonRosComm it seems that it's abbreviation is Not Ros Commponent, not Not Ros Communicating Commponet. And it makes a difference.
![image](https://github.com/twiniars/MeROS/assets/26524922/321954b6-46f4-4c26-bcc0-7c2c9027ef77)

Reason:    
Descriptive names are more readable and decrease enter barrier:  
![image](https://github.com/twiniars/MeROS/assets/26524922/d2b3f58a-66be-4ada-92fb-a450a6b46dc9)
 source:   
 https://thixalongmy.haugiang.gov.vn/media/1175/clean_code.pdf

**Comment by twiniars** [comment]
The problem is the length of the stereotypes that affect block size. Hence, the stereotypes are a trade-off between descriptiveness and constrained full length.

**Comment by czogran** [comment]
Block size is much easier to correct than readability. Current abbreviations could be confusing, As I presented on case of NonRosComm (it's abbreviation is from Not Ros Communicating Component,  Not Ros Component) it is confusing and dramatically increases enter barrier and could lead to concept misunderstanding.    
![image](https://github.com/twiniars/MeROS/assets/26524922/2b441ee1-1aaa-4ecd-8654-f40dfe1b1495)

**Comment by czogran** [comment]
Maybe adding spaces in stereotypes names could help?   
Usually they are written in camelCase, but I have not found a source that recommends this way of naming stereotypes.  
![image](https://github.com/twiniars/MeROS/assets/26524922/af0a532d-c017-4c2a-ae52-1aff5fe34363)
