### ISSUE TITLE
meros_vp_stereotypes.xml not contains all required stereotypes

### ISSUE THREAD

**Issue by czogran** [twiniars/MeROS#17]
meros_vp_stereotypes.xml should contain stereotypes mentioned in documentation.  However many of them is missing. For example:  
![image](https://github.com/twiniars/MeROS/assets/26524922/571befed-0710-43d0-b55d-3e57a43622bd)
![image](https://github.com/twiniars/MeROS/assets/26524922/cea2aeb4-b7bd-4bb1-a833-edb181f4ab32)
![image](https://github.com/twiniars/MeROS/assets/26524922/f4077d91-83c2-4c57-839d-5355e7f6a6ae)
![image](https://github.com/twiniars/MeROS/assets/26524922/9cc7e540-939d-4d30-9310-0343adea101a)

**Comment by twiniars** [comment]
New version 1.2 is under development. Version 1.1 will be deprecated.

**Comment by czogran** [comment]
First of all, MeROS releases  are numbered 1.2.3   
![Uploading image.png…]()    
 Hence, if you would like to increase from for example 1.1.2 to 1.2.1 it should be backward compatible.   

Moreover, I do not see a point to marking issue as completed when it is not :(
