### ISSUE TITLE
Namespace should refer to Node, not RunSystemCompon

### ISSUE THREAD

**Issue by czogran** [twiniars/MeROS#22]
According to documenentation Namespaces specialize nodes. Hence, in diagram Namespace should refer to Node. I am not sure with relation is the most proper: usage or containment. Maybe other. 

![image](https://github.com/twiniars/MeROS/assets/26524922/bb3d3e69-2f34-4327-b491-e084d9c3591f)

https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Launch/Using-ROS2-Launch-For-Large-Projects.html#namespaces
![image](https://github.com/twiniars/MeROS/assets/26524922/34111a41-f50d-4774-b046-6d54f2a59f34)

**Comment by twiniars** [comment]
Namespaces are more general, as it is stated in MeROS.
